# Generated by Django 4.1.6 on 2024-05-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewItem',
            new_name='Items',
        ),
    ]
