# Generated by Django 4.1.6 on 2024-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
    ]
